pandafile = open('panda.txt', 'w')
adjective = input('Enter an adjective: \n')
noun = input('Enter an noun: \n')
verb = input('Enter a verb: \n')
noun1 = input('Enter with another noun: \n')
pandafile.write( ('The %s panda walked to the %s and then %s. A nearby %s was unaffected by these events.') % (adjective, noun, verb, noun1))
pandafile.close()
pandafile = open('panda.txt')
readFile = pandafile.read()
print (readFile)
newtextFile = open('nextext.txt', 'w')
newtextFile.write(readFile)
newtextFile.close()